### ISSUE TITLE
mobile performance

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#219] opened 2017-12-11 01:34 UTC
First, just wanted to say this has been a wonderful library to work with! I absolutely love the functional approach to building animations. It makes things so much easier to compose and understand 🎉

I've been playing around with a bunch of demos and I am noticing the frame rate on my iPhone 6S isn't the best, even with the simple demos like [this one](https://codepen.io/popmotion/full/mqKyjd/). I'm curious if you have noticed this at all? I tried using `will-change` to see if that helped, but I didn't really notice any difference. Any ideas what could be causing this?  I've been testing with the beta, so apologies if I filed this too soon 😇

**Comment by souporserious** [comment] 2017-12-11 02:00
So I tried the same example on my girlfriend's iPhone 7 and it seemed to work fine 😅 I'm guessing something else is causing the perf issue on my phone.

**Comment by InventingWithMonster** [comment] 2017-12-11 08:18
Got the same thing on my 7 to be honest - it looks like it’s running at a stable 30fps which is bizarre.

**Comment by InventingWithMonster** [comment] 2017-12-11 08:18
Also glad to hear you’re enjoying it!

**Comment by InventingWithMonster** [comment] 2017-12-11 08:51
Weird. Trying the same page in simulator and there's no perf issues. You'd imagine it'd be worse.

**Comment by InventingWithMonster** [comment] 2017-12-11 09:56
So it seems like the issue is potentially when it runs in an iframe. If I run the same examples in the debug view they run at 60fps which is odd.

**Comment by souporserious** [comment] 2017-12-11 10:07
Ahh that sounds like it could be a culprit. I've only been testing in online code editors. I will test locally and report back.

**Comment by InventingWithMonster** [comment] 2017-12-11 11:33
I'm closing this ticket for now - this pen https://codepen.io/popmotion/pen/KZPXzz?editors=0010 proves that the problem lies with how rAF is handled in browsers (try on both desktop and iOS)

Very weird though, I've contacted CodePen to ask if they've seen it before because it feels like a massive problem to me!

**Closed by InventingWithMonster** 2017-12-11 11:33 UTC
