### ISSUE TITLE
BUG: complete event for values only fires once when completed when attached to a physics/decay.start()

### ISSUE THREAD

**Issue by cybervaldez** [Popmotion/popmotion#394] opened 2018-07-09 06:06 UTC
Issue: complete event on subscriptions and values would only fire once

Pen: https://codepen.io/anon/pen/qKgdQr?editors=0011

**Comment by Andarist** [comment] 2018-09-07 15:48
That's because the created `Observer` doesn't restart its `isActive` state. It sets it to `false` [here](https://github.com/Popmotion/popmotion/blob/291ed53cf51ed2529eb25012026d19e5cc9a6f95/packages/popmotion/src/observer/index.ts#L27) and it has to be `true` to fire `this.observer.complete();` 2 lines above.

I'm not sure if this is by design or not, because popmotion's streams are a little bit different from what I'm accustomed to.

But it seems to me that the behaviour should be changed - to either:
- allow for firing this complete for the second time
- or disallow updates after geting completed for the first time

@InventingWithMonster WDYT?

**Comment by lsimichael** [comment] 2018-11-03 20:14
This also affects value subscriptions

**Comment by alexpi** [comment] 2019-03-22 19:51
I am building a slider that uses the inertia action, and also value in order to be able to get velocity values for the action. How can I be notified that the slider has completed its motion since value, which as mentioned above only fires once?

**Comment by InventingWithMonster** [comment] 2020-01-21 11:11
Closing this as we're moving away from the reactive model

**Closed by InventingWithMonster** 2020-01-21 11:11 UTC
