### ISSUE TITLE
Popmotion will not compile

### ISSUE THREAD

**Issue by mswilson4040** [Popmotion/popmotion#374] opened 2018-06-11 23:12 UTC
**Describe the bug**
I recently upgraded popmotion-pose to the latest version and my project will no longer compile. It looks like there's an issue with the TS:

```
ERROR in node_modules/popmotion/lib/animations/decay/index.d.ts(2,39): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/decay/index.d.ts(2,62): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/decay/index.d.ts(2,68): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/decay/index.d.ts(2,70): error TS1005: ';' expected.
node_modules/popmotion/lib/animations/physics/index.d.ts(2,39): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/physics/index.d.ts(2,62): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/physics/index.d.ts(2,68): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/physics/index.d.ts(2,70): error TS1005: ';' expected.
node_modules/popmotion/lib/animations/spring/index.d.ts(2,39): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/spring/index.d.ts(2,62): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/spring/index.d.ts(2,68): error TS1005: ',' expected.
node_modules/popmotion/lib/animations/spring/index.d.ts(2,70): error TS1005: ';' expected.
node_modules/popmotion/lib/transformers.d.ts(5,63): error TS1005: ',' expected.
node_modules/popmotion/lib/transformers.d.ts(5,116): error TS1005: ',' expected.
node_modules/popmotion/lib/transformers.d.ts(5,149): error TS1005: ',' expected.
node_modules/popmotion/lib/transformers.d.ts(5,207): error TS1005: ';' expected.
node_modules/popmotion/lib/transformers.d.ts(5,209): error TS1128: Declaration or statement expected.
```

**To Reproduce**

Steps to reproduce the behavior from my repo:
1. Decompress the attached popmotion.zip
2. Open directory, and run `npm install`
3. Serve the application by running `ng serve`

Steps to reproduce the behavior from scratch:
1. Start new Angular app (`ng new popmotion-test`)
2. `npm install popmotion-pose`
3. Import pose into one of the components (`import pose from 'popmotion-pose';`)
4. Try and run the app `ng serve` and you will see the above output

**Expected behavior**
My project should compile
[popmotion.zip](https://github.com/Popmotion/popmotion/files/2092025/popmotion.zip)

**Link to CodePen or similar**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I am not sure, but it seems https://github.com/Popmotion/popmotion/issues/372 might be a similar issue.

**Comment by mswilson4040** [comment] 2018-06-12 16:17
I did a little more digging and narrowed it down to `popmotion v8.2.4` (from what it looks like). In my case, I am using `popmotion-pose` and when I upgraded it from `1.3.0` to `1.5.0` (which more than likely upgraded popmotion) it broke everything. When I reverted it back to `1.3.0` it was fine. It looks like this is very similar to https://github.com/Popmotion/popmotion/issues/372

**Comment by mswilson4040** [comment] 2018-06-12 16:51
I'm almost confident the issue resides in 8.2.4 now. 8.2.3 popmotion works fine. It looks like it's due to a new folder structure and the new syntax within the index.d.ts files. For example:

8.2.3 => node_modules/popmotion/animations/decay/index.d.ts

```
import { Action } from '../../action';
declare const _default: (props: {
    [key: string]: any;
}) => Action;
export default _default;
```

8.2.4 => node_modules/popmotion/lib/animations/decay/index.d.ts
```
import { Action } from '../../action';
declare const _default: (props: import("../../action/vector").Props) => Action;
export default _default;

```

The typescript compiler barfs at this line:
`declare const _default: (props: import("../../action/vector").Props) => Action;`

**Comment by InventingWithMonster** [comment] 2018-06-13 12:49
In `transformers.ts` we import the `Color` and `HSLA` types.

`type Color = RGBA | HSLA`

In the output declaration file, `Color` is output to `HSLA | import("../../../node_modules/style-value-types/lib/index").RGBA`

I can't import `RGBA` without using it explicitly so there must be a change I've made to the configuration to import undefined types in this way.

**Comment by InventingWithMonster** [comment] 2018-06-13 13:45
Narrowed this down to our Rollup process. `tsc` outputs the declarations as expected whereas Rollup is outputting the import stuff. I'll continue digging.

**Comment by InventingWithMonster** [comment] 2018-06-13 14:14
Narrowed it down to a bug in `2.9.x` - Fixed in `popmotion@8.2.5`

**Comment by mswilson4040** [comment] 2018-06-13 15:14
Awesome! Thank you!

**Comment by ptcampbell** [comment] 2018-09-21 21:19
Hey there — I think I'm having the same problem but with `react-pose` 3.1.1.

```
node_modules/popmotion/lib/reactions/value.d.ts(26,40): 
TS1005: ';' expected.

node_modules/popmotion/lib/reactions/value.d.ts(27,54):
TS1109: Expression expected.

node_modules/popmotion/lib/reactions/value.d.ts(29,5):
TS1128: Declaration or statement expected.
```

Happens only when building in production… 🤔

**Comment by axelhzf** [comment] 2018-10-22 09:04
I am having the same problem @ptcampbell. Using `react-pose@3.3.7` and getting

```
node_modules/popmotion/lib/reactions/value.d.ts(26,40): error TS1005: ';' expected.
node_modules/popmotion/lib/reactions/value.d.ts(27,54): error TS1109: Expression expected.
node_modules/popmotion/lib/reactions/value.d.ts(28,32): error TS1005: ',' expected.
node_modules/popmotion/lib/reactions/value.d.ts(28,52): error TS1005: ';' expected.
node_modules/popmotion/lib/reactions/value.d.ts(29,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(30,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(31,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(32,1): error TS1128: Declaration or statement expected.
```

The problem is this line

```
    scheduleVelocityCheck: () => import("framesync/lib/types").Process;
```

I tested it with typescript 2.8.1.

**Comment by axelhzf** [comment] 2018-10-24 08:16
I update the typescript version to `3.1.3` and the problem is fixed :)

**Closed** 2019-03-02 05:10 UTC

**Comment by z3phyro** [comment] 2019-03-11 07:32
+ popmotion@8.6.3
added 74 packages in 24.784s

λ tsc -v  (Typescript version)
Version 3.3.3333

ERROR in node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,47): error TS1005: ',' expected.
node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,78): error TS1005: ',' expected.
node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,84): error TS1005: ',' expected.
node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,132): error TS1005: ';' expected.
node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,230): error TS1005: ';' expected.
node_modules/@popmotion/popcorn/lib/utils/mix-color.d.ts(1,232): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(26,40): error TS1005: ';' expected.
node_modules/popmotion/lib/reactions/value.d.ts(27,54): error TS1109: Expression expected.
node_modules/popmotion/lib/reactions/value.d.ts(28,32): error TS1005: ',' expected.
node_modules/popmotion/lib/reactions/value.d.ts(28,52): error TS1005: ';' expected.
node_modules/popmotion/lib/reactions/value.d.ts(29,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(30,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(31,5): error TS1128: Declaration or statement expected.
node_modules/popmotion/lib/reactions/value.d.ts(32,1): error TS1128: Declaration or statement expected.

I've had this issue for a long time now. I solve it editing the this files manually but now we need another team member to prepare his dev environment and this still happens. I followed previous comments on the issue (updated typescript and popmotion) and I've seen no changes whatsoever. Could some one give me some help here?

Thanks in advance.

**Comment by mswilson4040** [comment] 2020-05-06 19:55
Looks like we are back to not compiling....

```
  5 import decay from './animations/decay';
           ~~~~~
  node_modules/popmotion/lib/index.d.ts:8:8 - error TS2613: Module '"D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/keyframes"' has no default export. Did you mean to use 'import { keyframes } from "D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/keyframes"' instead?
  
  8 import keyframes from './animations/keyframes';
           ~~~~~~~~~
  node_modules/popmotion/lib/index.d.ts:10:8 - error TS2613: Module '"D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/spring"' has no default export. Did you mean to use 'import { spring } from "D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/spring"' instead?
  
  10 import spring from './animations/spring';
            ~~~~~~
  node_modules/popmotion/lib/index.d.ts:12:8 - error TS2613: Module '"D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/tween"' has no default export. Did you mean to use 'import { tween } from "D:/a/1/s/wwwroot/ClientApp/node_modules/popmotion/lib/animations/tween"' instead?
  
  12 import tween from './animations/tween';
```

**Comment by stokesman** [comment] 2020-05-08 22:09
It looks like the same thing that was causing #878. So it likely works now if you'll freshen the install.
