### ISSUE TITLE
React Pose: applyAtStart / applyAtEnd display: none / block preventing transition

### ISSUE THREAD

**Issue by neagle** [Popmotion/popmotion#698] opened 2019-01-16 15:09 UTC
## Describe the bug
Using enter/exit poses, and using `applyAtStart: { display: 'block' }` and `applyAtEnd: { display: 'none' }` (which is a highly useful pattern), transforming the `y` value (at least) fails to transition for the exit → enter pose. Enter → exit seems to work as expected.

## How to reproduce
1. Go to [this sandbox](https://codesandbox.io/s/6xr2oylyk3)
2. Observe that the Notification fades in (opacity transition), but does not transition downward.
3. Observe that the Notification fades out _and_ transitions upward on exit.
4. In `index.js`, comment out the `applyAtStart` and `applyAtEnd` keys in the Notification pose config.
5. Note that the initial transition now fades in and transitions downward, as desired.
6. If you change `display: 'none|block'` to `visibility: 'hidden|visible'`, the transition also seems to work properly. This seems uniquely related to an element that was set to `display: none`.

## Link to CodeSandbox example
https://codesandbox.io/s/6xr2oylyk3

## Device information
In which environment are you reproducing the bug?
 - Device: MBP
 - OS: OSX
 - Browser: Chrome
 - Version: 71.0.3578.98

## Additional context
I apologize if I am missing anything obvious. Thanks for this tremendous library!

**Comment by Andarist** [comment] 2019-01-20 18:13
Seems like this might be a duplicate of https://github.com/Popmotion/popmotion/issues/491 . Could you @neagle confirm / deny it? 

I'll try to think about this to see if I can fix it.

**Closed** 2020-01-20 14:56 UTC
Labels: Pose is deprecated
