### ISSUE TITLE
react-pose: List items rendering are not animated while reordering

### ISSUE THREAD

**Issue by OogieBoogieInJSON** [Popmotion/popmotion#671] opened 2018-12-18 15:25 UTC
## Describe the bug
A wrapped component with posed is not animated when it is part of list and other elements are being removed.

## How to reproduce
Codesandbox: https://codesandbox.io/s/yl5ll81xj

You can see that every second an element is removed from state but no animation is happening. If I switch back to shuffle method (line 23), the animations work. But, if I directly use a posed element (see line 15) then it works even when removing an element.

## Device information
In which environment are you reproducing the bug?
 - Device: Desktop
 - OS: Windows 10
 - Browser Chrome 
 - Version 70

## Additional context
I've read the entire documentation. Is it a bug or am I missing something I have to do in this case. Thanks.

**Comment by Andarist** [comment] 2018-12-18 17:42
Based on the fact that this works with `const Item = posed.li({});` I would consider it as a bug. Thanks for the reported issue and the clear reproduction. I'm gonna dive into it when I get some time.

**Comment by Andarist** [comment] 2018-12-18 18:21
So it's not a bug, you have to pass `style` prop received from `PoseGroup` - https://codesandbox.io/s/zk02yj0194 .

**Comment by OogieBoogieInJSON** [comment] 2018-12-18 20:04
Oh I see. In the documentation example it was passing them as ...props but I haven't done that. Is there are prop I have to specifically pass to my element? I should've logged the props and take a closer look. Thank you, I will try tomorrow and hope it works in project. :heart:

**Comment by Andarist** [comment] 2018-12-18 22:39
In this case I think only the `style` prop has to be passed down

**Comment by Andarist** [comment] 2018-12-19 12:48
Glad I could help, you can close the issue (I don't have such permissions).

**Closed** 2018-12-19 15:32 UTC
