### ISSUE TITLE
React Pose: `onPoseComplete` firing at unexpected times.

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#346] opened 2018-05-22 08:45 UTC
Allegedly firing at the start of an animation. I think part of this problem is that the callback thats fired when an animation completes is the one present on the component at that moment of time, rather than the one present when the animation was started.

We could bind callbacks when an animation starts using a weakmap

**Comment by Andarist** [comment] 2018-09-29 11:49
Do u know how to reproduce the issue? I could work on fixing it then.

**Comment by carlosagsmendes** [comment] 2019-02-28 21:37
@Andarist and @InventingWithMonster I think I have [repro in this codesandbox](https://yqmrop03mj.codesandbox.io/)

- Click on the first box: the pose changes but nothing is logged to the console (expected: 'fullscreen')
- Click on the first box again to close it and nothing is logged
- Click on the second box to open it and again to close it. On both times, the pose changes and '["enter", "flip"]' is logged to the console (expected 'fullscreen' on the first click)
- Now if you click on the third box, '["enter", "flip"] ["enter", "flip"]' will be logged to the console

Three unexpected things (for me): 

1) 'fullscreen' is never logged to the console
2) the number of logged items using onPoseComplete increases proportionally with the number of items that had their pose changed 
3) clicking on the first box never logs to the console, even after logging starts working for the other boxes

Please note that I'm using both **PoseGroup** and **forwardRef**

Hope it helps

**Comment by Andarist** [comment] 2019-02-28 22:13
> * 'fullscreen' is never logged to the console

That's because your PoseGroup rerenders too and it marks PosedBox as entering - which is a bug. This happens specifically because of how [those lines](https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/Transition/children.ts#L96-L101) are handled. We should improve this algorithm, we could maybe search for some inspiration on how this might be handled [here](https://github.com/react-spring/react-spring/blob/47bd19e28051f983d0fe29054af3e399dd0d80f9/src/useTransition.js#L155)

> * the number of logged items using onPoseComplete increases proportionally with the number of items that had their pose changed

Probably it happens for the same reason.

**Comment by carlosagsmendes** [comment] 2019-02-28 22:23
Thank you @Andarist. I'll take a look at your links but I'm not sure I will able to create a PR , but I'll start by creating a failing text. 

In the meanwhile, is there any alternative to find that the 'fullscreen' transition has ended inside the custom component (forwardRef)? 

I need to hide its contents while animating, but I'm out of ideas on how to do so without being able to use onPoseComplete.

**Closed** 2020-01-20 14:58 UTC
Labels: Bug, PRs accepted, Pose is deprecated
