### ISSUE TITLE
Pose route transition with Gatsby

### ISSUE THREAD

**Issue by bogdancss** [Popmotion/popmotion#450] opened 2018-08-29 14:04 UTC
I have a site running on Gatsby v1 and want to get rid of the way Gatsby handles route transitioning as it creates a bunch of issues when accessing generated pages for the first time (the page hangs in the `entering` state and never renders fully).

This is  the `layout` component which wraps all other pages:
```
      <div>
        <Helmet>...</Helmet>
        <Header/>
        <Menu/>
        <PoseGroup>
          <MainWrapper key={this.props.location.key}>
            {this.props.children()}
          </MainWrapper>
        </PoseGroup>
        <Footer/>
      </div>
```
(`this.props.location.key` changes every time the route updates)
And this is the `MainWrapper`:
```
const MainWrapper = posed.div({
  enter: { opacity: 1, delay: 300 },
  exit: { opacity: 0 }
})
```

The children don't have any animations, I just want to simply fade out the current page, and fade in the next one.

What is currently happening is, the next page renders in immediately, then it fades out and back in. I tried adding the `beforeChildren` config, but that doesn't seem to do anything.

**Comment by InventingWithMonster** [comment] 2018-08-29 16:01
That's weird. It sounds like like the contents of `MainWrapper` is changing when it shouldn't, and I suspect this is because `children` is a function. I'm not sure why that's an issue but it clearly is.

What is actually happening is the two `MainWrapper` components are animating in and out properly, but the contents of the first one is changing to the new stuff (again because it's a function)

Maybe try removing `MainWrapper` and instead wrapping the components returned from `children` in a similar posed component, again with a unique key?

**Comment by b0gd4n** [comment] 2018-08-29 16:08
ok - will give that a go

**Comment by InventingWithMonster** [comment] 2018-08-31 10:47
@b0gd4n any update?

**Comment by JosNun** [comment] 2018-09-02 01:35
@b0gd4n Did you ever get this working?

**Comment by JosNun** [comment] 2018-09-02 19:53
Okay, maybe I'm missing something, but isn't wrapPageElement, which is used in gatsby-browser.js only available when using gatsby-plugin-layout, which, in-turn, is a Gatsby v2 thing? Additionally, the PR you linked is for Gatsby v2 as well, so... I'm not exactly sure how you got it working 🙁

**Comment by b0gd4n** [comment] 2018-09-02 19:55
@JosNun ah - I actually updated to v2 over the weekend. But I was using the gatsby-browser in v1 as well, so I think it should have the same setup.

**Comment by InventingWithMonster** [comment] 2018-09-03 15:34
@b0gd4n Is this issue closed then? Thanks for taking a look at it, hopefully I can convert this to a tutorial soon

**Comment by b0gd4n** [comment] 2018-09-03 15:37
there is one issue I spotted - in my case, I have the `Header` and `Footer` outside the `Posed` element. This basically makes a duplicate of the header and footer elements and you can see them both underneath each other for a brief moment. Will try and figure out how to get around it.

**Comment by MrLoh** [comment] 2018-09-04 20:46
I have the same issue as originally described here, but my setup is using after.js. Is there any idea what could be causing the weird flickering in the transition. Maybe the other problem you have could be moved to a new issue, it seems rather unrelated. 

![pose-route-transition-flicker](https://user-images.githubusercontent.com/1285032/45056843-54411580-b094-11e8-8ca4-2aeebeeffc9f.gif)

**Comment by Polcius** [comment] 2018-11-06 04:11
@b0gd4n That's a great solution. I was trying to do the same for a while until I stumbled upon your code. There must be a more optimal way to do it, but it works :)

**Comment by Polcius** [comment] 2018-11-06 04:39
[Here is another way](https://github.com/VilhelmNielsen/gatsby-with-react-pose). His way is wrapping all the pages with Layout & PoseGroup in gatsby-browser.js. Less code but I guess less control over Layout and Transitions?

In gatsby-browser:

`import React from 'react'
import posed, { PoseGroup } from 'react-pose'
import Layout from './src/components/layout'

const Transition = posed.div({
  enter: { opacity: 1, delay: 300, beforeChildren: true },
  exit: { opacity: 0 },
})

export const replaceComponentRenderer = ({ props, ...other }) => {
  const { component } = props.pageResources
  return (
    <Layout>
      <PoseGroup>
        <Transition key={props.location.key}>
          {React.createElement(component, props)}
        </Transition>
      </PoseGroup>
    </Layout>
  )
}`

**Closed** 2020-01-20 14:58 UTC
Labels: Pose is deprecated
